### ISSUE TITLE
Some Qt & Qml sources

### ISSUE THREAD

**Issue by Vitaee** [rigtorp/awesome-modern-cpp#116]
Thanks for sharing many sources about c++. I am sad to discovered it now.

I will make a suggestion. 
Maybe should put QML and Qt frameworks sources. From this repository users who wants to learn that frameworks can reach or find new sources quickly.

Let me [start.](https://riptutorial.com/ebook/qt)

Thanks in advance.

**Comment by arunpkqt** [comment]
@Vitaee here is another Repo that has a list of awesome Qt & QML libraries & modules.
https://github.com/mikalv/awesome-qt-qml

**Comment by Vitaee** [comment]
Thank you @arunpkqt, I didn't know that happy to find new resources.
