### ISSUE TITLE
some best practices suggestions

### ISSUE THREAD

**Issue by matkatmusic** [rigtorp/awesome-modern-cpp#79]
some Audio Developers Conferences talks:
https://www.youtube.com/watch?v=Q0vrQFyAdWI & https://www.youtube.com/watch?v=PoZAo2Vikbo 2-part talk from the Tracktion developers.
https://www.youtube.com/watch?v=Q97LBXqgMus <- might be too specific to audio development for your list.

**Comment by rigtorp** [comment]
Thank you @matkatmusic. Took a quick look. Maybe it's interesting from a
audio developer perspective, but there are better concurrency primitives
such as RCU, hazard pointer, seqock that solves these problems better. They
show a poor implementation of spinlock.
